spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelaria?useSSL=false
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect